baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-stack"
paginate = 5
title = "謝宗晅"
disqusShortname = "vincentthh35"            # Change it to your Disqus shortname before using
DefaultContentLanguage = "en"                   # Theme i18n support
# ignoreErrors = ["error-remote-getjson"]
googleAnalytics = "G-Y5NYJ89B2V"

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[params]
    # enable math render
    math = true

    mainSections = ["post"]
    featuredImageField = "image"
    rssFullContent = true
    # clearReading = true
    favicon = "/img/favicon.png"
    [params.colorScheme]
        toggle = true
        default = "dark"
    [params.footer]
        since = 2020
        customText = ""
    [params.dateFormat]
        published = "Jan 02, 2006"
        lastUpdated = "Jan 02, 2006 15:04 MST"

    [params.sidebar]
        subtitle_1 = "NTU CSIE B07"
        subtitle_2 = "Trader @ Kronos"
        compact = false

        # emoji = "🍥"
        [params.sidebar.avatar]
            local = true
            src = "img/avatar.jpg"



    [params.article]
        math = false
        [params.article.license]
            enabled = true
            default = "Licensed under CC BY-NC-SA 4.0"

    [params.comments]
        enabled = true
        provider = "disqus"         # Available: disqus, utterances
        [params.comments.utterances]
            repo = ""
            issueTerm = "pathname"
            label = ""             # Optional
            theme = "preferred-color-scheme"

    [params.widgets]
        enabled = ['archives'] # 'tag-cloud'
        [params.widgets.archives]
            limit = 5
            ### Archives page relative URL
            path = "archives"
        [params.widgets.tagCloud]
            limit = 10

    [params.opengraph]
        [params.opengraph.twitter]
            site = ""
            card = "summary_large_image"

    [params.defaultImage]
        [params.defaultImage.opengraph]
            enabled = false
            local = false
            src = ""

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = -100
        pre = "home"
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "about"
        weight = -90
        pre = "user"
    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "archives"
        weight = -70
        [menu.main.params]
            icon = "archives"
            newTab = false
        
    [[menu.social]]
        identifier = "github"
        name = "github"
        url = "https://github.com/vincentthh35"
        weight = -30
        [menu.social.params]
            icon = "brand-github"
            newTab = true
    [[menu.social]]
        identifier = "linkedin"
        name = "linkedin"
        url = "https://www.linkedin.com/in/vincentthh/"
        weight = -20
        [menu.social.params]
            icon = "brand-linkedin"
            newTab = true
    [[menu.social]]
        identifier = "cv"
        name = "cv"
        url = "/files/CV_latex.pdf"
        weight = -10
        [menu.social.params]
            icon = "file-text"
            newTab = true
    [[menu.social]]
        identifier = "email"
        name = "email"
        url = "mailto:vincentthh35@gmail.com"
        weight = -5
        [menu.social.params]
            icon = "mail"
            newTab = false


[related]
    includeNewer = true
    threshold = 60
    toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 200

[markup]
    # defaultMarkdownHandler = "blackfriday"
    [markup.goldmark.renderer]
        # for render HTML inside .md
        unsafe = true
        #############
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "dracula"
        tabWidth = 4
